-- Database: babyfoot

-- DROP DATABASE babyfoot;
    
CREATE TABLE PLAYER
	(
     id_p INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY ,
     pseudo CHAR(30)
    );

CREATE TABLE ENCOUNTERS
	(
     id_e INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,  
     player1 INT, 
     player2 INT,
     state_e BOOLEAN DEFAULT true;
    );
    
 CREATE TABLE MATCHS
	(
     id_m INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
     state_match CHAR(30),
     result_match CHAR(30),
     id_e INT,
        FOREIGN KEY (id_e) REFERENCES ENCOUNTERS (id_e)
    );

INSERT INTO PLAYER(pseudo) VALUES ('Elisa');
INSERT INTO PLAYER(pseudo) VALUES ('Tristan');
INSERT INTO PLAYER(pseudo) VALUES ('Adil');
INSERT INTO PLAYER(pseudo) VALUES ('Lea');
INSERT INTO PLAYER(pseudo) VALUES ('Adele');
INSERT INTO PLAYER(pseudo) VALUES ('Loic');


INSERT INTO MATCHS (state_match,result_match,id_e) VALUES ('start',null,1);
INSERT INTO MATCHS (state_match,result_match,id_e) VALUES ('end','P2 wins',2);


INSERT INTO ENCOUNTERS(player1,player2) VALUES ('Elisa','Adil');
INSERT INTO ENCOUNTERS(player1,player2,state_e) VALUES ('Germaine','Tristan',false);
INSERT INTO ENCOUNTERS(player1,player2) VALUES ('Lea','Adele');
INSERT INTO ENCOUNTERS(player1,player2) VALUES ('Lulu','Loulou');
INSERT INTO ENCOUNTERS(player1,player2,state_e) VALUES ('Riri','Fifi',false);
INSERT INTO ENCOUNTERS(player1,player2,state_e) VALUES ('Donald','Picsou',false);


 --------
SELECT *
 FROM (SELECT MATCHS.id_e as idesub, MATCHS.id_m as idmsub, 
       MATCHS.state_match as substate, MATCHS.result_match as subresult,
       ENCOUNTERS.idp1 as subidp1, ENCOUNTERS.idp2 as subidp2
 FROM MATCHS
 JOIN ENCOUNTERS
 ON MATCHS.id_e = ENCOUNTERS.id_e
 JOIN PLAYER
 ON ENCOUNTERS.idp1 = PLAYER.id_p
 ) as SUB
 JOIN PLAYER
 ON SUB.subidp2 = PLAYER.id_p
 ;



------------------------ SELECTIONNE RENCONTRE, IDPLAYER, PSEUDOS


SELECT id_e, state_e, idplayer1, pseudoPlayer1, id_p as idPlayer2, pseudo as pseudoplayer2
FROM PLAYER
JOIN (
    SELECT id_p as idPlayer1, pseudo as pseudoPlayer1, id_e, idp1, idp2, state_e
FROM PLAYER
JOIN ENCOUNTERS
ON ENCOUNTERS.idp1 = PLAYER.id_p
) as SUB
ON PLAYER.id_p = SUB.idp2; 

------------------- MATCH, RENCONTRE, PSEUDO

SELECT id_m, state_match, result_match, idplayer1, pseudoPlayer1,idplayer2, pseudoPlayer2
FROM (
    SELECT id_e, idplayer1, pseudoPlayer1, id_p as idPlayer2, pseudo as pseudoplayer2
FROM PLAYER
JOIN (
    SELECT id_p as idPlayer1, pseudo as pseudoPlayer1, id_e, idp1, idp2
FROM PLAYER
JOIN ENCOUNTERS
ON ENCOUNTERS.idp1 = PLAYER.id_p
) as SUB
ON PLAYER.id_p = SUB.idp2
) as SUB2
JOIN MATCHS
ON SUB2.id_e = MATCHS.id_e;